CREATE TABLE [dbo].[Uzivatel]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [Login] NVARCHAR(50) NOT NULL UNIQUE,
    [Heslo] NVARCHAR(MAX) NOT NULL,
    [Jmeno] NVARCHAR(100) NOT NULL,
    [Prijmeni] NVARCHAR(100) NOT NULL,

    [Ulice] NVARCHAR(100) NOT NULL,
    [CisloPopisne] NVARCHAR(16) NULL,
    [CisloOrientacni] NVARCHAR(16) NULL,
    [PSC] NVARCHAR(16) NOT NULL,
    [Mesto] NVARCHAR(100) NOT NULL,
    [Okres] NVARCHAR(100) NOT NULL,
    [Kraj] NVARCHAR(100) NOT NULL,
    [Zeme] NVARCHAR(100) NOT NULL,
    
    [Email1] NVARCHAR(100) NOT NULL,
    [Email2] NVARCHAR(100) NULL,
    [Telefon1] NVARCHAR(20) NOT NULL,
    [Telefon2] NVARCHAR(20) NULL,
)
