/*
Seznam ekonomických subjektů
	https://www.czso.cz/csu/czso/registr-ekonomickych-subjektu-otevrena-data-dokumentace
	https://opendata.czso.cz/data/od_org03/res_data.csv

	Použité číselníky a klasifikace – odkazy pro stažení obsahu:

	Číselník okresů -  kód číselníku ČSÚ 109: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=109&typdat=0&cisjaz=203&format=2&separator=%2C

	Právní forma organizace -  kód číselníku ČSÚ 56:  https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=56&typdat=0&datpohl=31.12.2021&cisjaz=203&format=2&separator=%2C

	Číselník krajů - kód číselníku ČSÚ 108 https://apl.czso.cz/iSMS/cisdata.jsp?kodcis=108

- res_data.xml - seznam ekonomických subjektů
- CIS0109_CS.csv - Číselník okresů
- CIS0056_CS.csv - Právní forma organizace
- CIS0108_CS.csv - číselník krajů
*/
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (8, N'krabicezvinice s.r.o.', N'Společnost s r.o.', N'10859705')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (18, N'Ing. Zdeněk Kuneš s.r.o.', N'Společnost s r.o.', N'7157738')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (28, N'Farma Debrné s.r.o.', N'Společnost s r.o.', N'28848691')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (38, N'Goyo ADV s.r.o.', N'Společnost s r.o.', N'17985641')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (48, N'DOFEK, s.r.o.', N'Společnost s r.o.', N'26230712')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (58, N'HENS company s.r.o.', N'Společnost s r.o.', N'28317025')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (68, N'Bighusky s.r.o.', N'Společnost s r.o.', N'28628888')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (78, N'UVED Company, s.r.o.', N'Společnost s r.o.', N'1780565')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (88, N'Naveera Galaxy s. r. o.', N'Společnost s r.o.', N'17528852')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (98, N'101 km s.r.o.', N'Společnost s r.o.', N'28239008')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (108, N'KHIM Bohemia s.r.o.', N'Společnost s r.o.', N'28359909')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (118, N'DPS Domov Lucie, s.r.o.', N'Společnost s r.o.', N'9546499')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (128, N'Římskokatolická farnost Bakov nad Jizerou', N'Evid.círk.práv.osoby', N'42716861')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (138, N'CRS Credit Service, s.r.o.', N'Společnost s r.o.', N'24288896')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (148, N'VOGLIA D´OSMICA s.r.o.', N'Společnost s r.o.', N'26457181')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (158, N'Kovářské výhně s.r.o.', N'Společnost s r.o.', N'28811712')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (168, N'Franklin Travel s.r.o.', N'Společnost s r.o.', N'3592839')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (178, N'Gold Harmony SPA s.r.o.', N'Společnost s r.o.', N'7117302')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (188, N'CIAO CZ s.r.o. v likvidaci', N'Společnost s r.o.', N'25501232')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (198, N'Bytové družstvo domu 1083', N'Družstvo', N'25817221')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (208, N'Fabrika na ploty s.r.o.', N'Společnost s r.o.', N'17616239')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (218, N'ABiP s.r.o.', N'Společnost s r.o.', N'27734811')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (228, N'PPmaison s.r.o.', N'Společnost s r.o.', N'9093737')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (238, N'Zlatá lvice s.r.o.', N'Společnost s r.o.', N'9256083')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (248, N'Římskokatolická farnost Šlapanice u Brna', N'Evid.círk.práv.osoby', N'65341775')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (258, N'Honební společenstvo Pyšely', N'Honební společenstvo', N'70567174')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (268, N'SIT s.r.o.  v likvidaci', N'Společnost s r.o.', N'61678414')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (278, N'Tenenbaum Invest s.r.o.', N'Společnost s r.o.', N'28299850')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (288, N'IROLAN INTERNATIONAL s.r.o.', N'Společnost s r.o.', N'29042747')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (298, N'JV holdings s.r.o.', N'Společnost s r.o.', N'6710832')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (10, N'ÁBRÁNYI  spol. s r.o.', N'Společnost s r.o.', N'25543113')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (20, N'BAULAND TECH s.r.o.', N'Společnost s r.o.', N'4111460')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (30, N'SOLAREC s.r.o.', N'Společnost s r.o.', N'27741753')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (40, N'Nedbal Trading s.r.o.', N'Společnost s r.o.', N'29320372')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (50, N'UNIREAL Praha, s.r.o.', N'Společnost s r.o.', N'25053531')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (60, N'AZ PLASTIK Praha s.r.o.', N'Společnost s r.o.', N'25148095')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (70, N'Vázací prostředky, s.r.o.', N'Společnost s r.o.', N'3865860')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (80, N'AVOMERI linen s.r.o.', N'Společnost s r.o.', N'6920632')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (90, N'Prag Sun System s.r.o.', N'Společnost s r.o.', N'17189748')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (100, N'Maxexpo s.r.o.', N'Společnost s r.o.', N'7647603')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (110, N'LIKASPO, spol. s r.o.- v likvidaci', N'Společnost s r.o.', N'25534629')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (120, N'POZEMSTAV Prostějov - servis, s.r.o.', N'Společnost s r.o.', N'25546244')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (130, N'Runex - Running & Exercise s.r.o.', N'Společnost s r.o.', N'6626645')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (140, N'Panthera Capital s.r.o.', N'Společnost s r.o.', N'6024912')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (150, N'ananasana design s.r.o.', N'Společnost s r.o.', N'8692611')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (160, N'Consped s.r.o.', N'Společnost s r.o.', N'28872398')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (170, N'FEBE Energy s.r.o.', N'Společnost s r.o.', N'10792139')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (180, N'DIAMANT BROKERS spol. s r.o., v likvidaci', N'Společnost s r.o.', N'62739085')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (190, N'VETREAL MB s.r.o.', N'Společnost s r.o.', N'7730004')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (200, N'Stable Work Services s.r.o.', N'Společnost s r.o.', N'7406835')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (210, N'GYROSCOPE s.r.o.', N'Společnost s r.o.', N'8142921')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (220, N'BEST GOLD CARS s.r.o.', N'Společnost s r.o.', N'8371300')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (230, N'STATIX s.r.o.', N'Společnost s r.o.', N'62025244')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (240, N'Sport-Racing-Bike s.r.o.', N'Společnost s r.o.', N'29269784')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (250, N'U PAŘÍŽANA s.r.o.', N'Společnost s r.o.', N'11936169')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (260, N'JN DAPO Plus s.r.o.', N'Společnost s r.o.', N'28097157')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (270, N'DOTRONA s.r.o.', N'Společnost s r.o.', N'2092972')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (280, N'Snark&Snark, s.r.o.', N'Společnost s r.o.', N'24852589')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (290, N'START Louny s.r.o. v likvidaci', N'Společnost s r.o.', N'49097300')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (300, N'NIMBUS Architects s.r.o.', N'Společnost s r.o.', N'28881265')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (7, N'Saab Technologies, s.r.o.', N'Společnost s r.o.', N'27616371')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (17, N'International Insurance Brokers s.r.o.', N'Společnost s r.o.', N'26474603')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (27, N'CYKLOS Brno spol. s r. o.', N'Společnost s r.o.', N'25323997')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (37, N'Michovský - TOOLS s.r.o.', N'Společnost s r.o.', N'26209713')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (47, N'MOLLKA TRADE s.r.o.', N'Společnost s r.o.', N'28348133')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (57, N'KOREFIB s.r.o.', N'Společnost s r.o.', N'17587921')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (67, N'YIT Stavo s.r.o.', N'Společnost s r.o.', N'26420562')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (77, N'SAROH s.r.o.', N'Společnost s r.o.', N'9710884')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (87, N'Asiameu Investment and Development Group s.r.o. v likvidaci', N'Společnost s r.o.', N'5640024')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (97, N'PROTIVENSKIY s.r.o.', N'Společnost s r.o.', N'27389707')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (107, N'Esteit Invest s.r.o.', N'Společnost s r.o.', N'27630579')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (117, N'Císařský ostrov s.r.o.', N'Společnost s r.o.', N'5401241')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (127, N'CHINAMED s.r.o.', N'Společnost s r.o.', N'25195093')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (137, N'Four Service, s.r.o.', N'Společnost s r.o.', N'25332775')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (147, N'AWA ENERGO s.r.o.', N'Společnost s r.o.', N'11702401')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (157, N'DENETHOR THREE s.r.o.', N'Společnost s r.o.', N'8974586')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (167, N'Anpore s.r.o.', N'Společnost s r.o.', N'7993200')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (177, N'PPA - Prague Party Agency spol. s r.o.', N'Společnost s r.o.', N'28389433')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (187, N'BV-DROB CZ, s.r.o.', N'Společnost s r.o.', N'10961241')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (197, N'HOTEL AMETYST s.r.o.', N'Společnost s r.o.', N'49708872')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (207, N'Contact Boss s.r.o.', N'Společnost s r.o.', N'3675360')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (217, N'Parker Hannifin Industrial s.r.o.', N'Společnost s r.o.', N'25415123')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (227, N'Endokrina s.r.o.', N'Společnost s r.o.', N'4471997')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (237, N'ALVA GASTRO s.r.o.', N'Společnost s r.o.', N'28966864')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (247, N'Just Energy s.r.o.', N'Společnost s r.o.', N'17731747')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (257, N'FOR MARK s.r.o.', N'Společnost s r.o.', N'29448395')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (267, N'TROPICAL ANIMALS, s.r.o. v likvidaci', N'Společnost s r.o.', N'27060799')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (277, N'FOSFIT a.s. v likvidaci', N'Akciová společnost', N'24846708')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (287, N'Agentura 2007, s.r.o. v likvidaci', N'Společnost s r.o.', N'28002938')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (297, N'Pečivo MALINOVÁ s.r.o.', N'Společnost s r.o.', N'27970566')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (5, N'Agrisun 99 s.r.o.', N'Společnost s r.o.', N'17469571')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (15, N'GEODETI-PLZEŇ s.r.o.', N'Společnost s r.o.', N'4317378')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (25, N'Trade Signal Services s.r.o.', N'Společnost s r.o.', N'9395521')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (35, N'DUBROVNIK s.r.o.', N'Společnost s r.o.', N'28987942')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (45, N'DOMY SENIORŮ gama, s.r.o. v likvidaci', N'Společnost s r.o.', N'1389394')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (55, N'H.SV Podluží s.r.o.', N'Společnost s r.o.', N'29313252')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (65, N'TCM TransCom Group s.r.o.', N'Společnost s r.o.', N'27772616')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (75, N'RC Truck Models  s.r.o.', N'Společnost s r.o.', N'11667869')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (85, N'Marine Energy s.r.o.', N'Společnost s r.o.', N'6908420')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (95, N'Art Colonial, s.r.o.', N'Společnost s r.o.', N'28592531')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (105, N'AM PRODEJNY POTRAVIN s.r.o. v likvidaci', N'Společnost s r.o.', N'28653521')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (115, N'MONICA SPORTSWEAR, s.r.o. v likvidaci', N'Společnost s r.o.', N'25102737')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (125, N'F01 s.r.o.', N'Společnost s r.o.', N'7744897')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (135, N'Société privée s.r.o.', N'Společnost s r.o.', N'9294422')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (145, N'FALEVA CORPORATION s.r.o.', N'Společnost s r.o.', N'9237216')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (155, N'Vinotéka u nádraží s.r.o.', N'Společnost s r.o.', N'3459578')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (165, N'PULSAR spol. s r.o.', N'Společnost s r.o.', N'61852791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (175, N'STAR ARENA s.r.o.', N'Společnost s r.o.', N'7375697')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (185, N'HP horse power, s.r.o. - "v likvidaci"', N'Společnost s r.o.', N'26246791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (195, N'Delator System s.r.o.', N'Společnost s r.o.', N'3818578')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (205, N'Shardana s.r.o.', N'Společnost s r.o.', N'27135063')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (215, N'ASANELI s.r.o.', N'Společnost s r.o.', N'26901285')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (225, N'BRNOMETAL, spol. s r.o. v likvidaci', N'Společnost s r.o.', N'44017588')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (235, N'A3 architects s.r.o.', N'Společnost s r.o.', N'1776975')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (245, N'V+K INVEST s.r.o.', N'Společnost s r.o.', N'41690419')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (255, N'by wood.store s.r.o.', N'Společnost s r.o.', N'5770696')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (265, N'NAKAMOTOX CZ, s. r. o. v likvidaci', N'Společnost s r.o.', N'6587305')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (275, N'TeCon CZ s.r.o.', N'Společnost s r.o.', N'25447424')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (285, N'FinTech Bohemia s.r.o.', N'Společnost s r.o.', N'26874709')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (295, N'PILATRANS ZEJDA s.r.o.', N'Společnost s r.o.', N'27739023')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (6, N'SAFACAFE s.r.o. v likvidaci', N'Společnost s r.o.', N'28921275')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (16, N'ADELE s.r.o.', N'Společnost s r.o.', N'6247563')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (26, N'FRYDRYCH - ELEKTRO s.r.o.', N'Společnost s r.o.', N'27269400')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (36, N'originální porcelán.cz s.r.o.', N'Společnost s r.o.', N'4101863')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (46, N'Shisha café bar s.r.o.', N'Společnost s r.o.', N'7565291')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (56, N'Moravská Bezpečnostní Služba s.r.o.', N'Společnost s r.o.', N'11806711')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (66, N'RENTNER HAUS - RASL s.r.o.', N'Společnost s r.o.', N'4313704')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (76, N'RYO stavební s.r.o.', N'Společnost s r.o.', N'26836114')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (86, N'AMBONAT, s.r.o. "v likvidaci"', N'Společnost s r.o.', N'25354558')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (96, N'MARTINA NEMOVITOSTI s.r.o.', N'Společnost s r.o.', N'4095189')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (106, N'WP - STAV s.r.o. v likvidaci', N'Společnost s r.o.', N'25302744')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (116, N'Silenos Works s.r.o.', N'Společnost s r.o.', N'9193651')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (126, N'GIULIA INVEST s.r.o.', N'Společnost s r.o.', N'28272145')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (136, N'AB TRANS s.r.o.', N'Společnost s r.o.', N'7514930')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (146, N'Plexiweiss  s.r.o.', N'Společnost s r.o.', N'27717267')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (156, N'MYRMELEON s.r.o.', N'Společnost s r.o.', N'24731099')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (166, N'Kladno Development Group s.r.o.', N'Společnost s r.o.', N'8351791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (176, N'MATEICIUC a.s.', N'Akciová společnost', N'60792825')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (186, N'Nadační fond Zdeňky Horníkové v likvidaci', N'Nadace', N'26003490')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (196, N'Mateo Solutions a.s.', N'Akciová společnost', N'9218807')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (206, N'AGRO Rakšice, spol. s r. o.', N'Společnost s r.o.', N'27740951')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (216, N'N3XT s.r.o.', N'Společnost s r.o.', N'25761226')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (226, N'LPS Consulenza, s.r.o.', N'Společnost s r.o.', N'27626211')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (236, N'RYSK stavebně obchodní společnost, spol. s r.o. v likvidaci', N'Společnost s r.o.', N'47539950')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (246, N'Pascal s.r.o.', N'Společnost s r.o.', N'4820665')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (256, N'D1net s.r.o.', N'Společnost s r.o.', N'28061179')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (266, N'Tech Lex s.r.o.', N'Společnost s r.o.', N'4715764')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (276, N'Bydlení pro všechny, z.ú.', N'Ústav', N'5549434')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (286, N'Že-Stav, s.r.o.', N'Společnost s r.o.', N'27697347')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (296, N'BORILLO BAU s.r.o.', N'Společnost s r.o.', N'3982947')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (2, N'CONFORMAT s.r.o.', N'Společnost s r.o.', N'26974282')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (12, N'EXELERO TRADE & INVESTMENT, s.r.o. v likvidaci', N'Společnost s r.o.', N'24852171')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (22, N'Nákupátor s.r.o.', N'Společnost s r.o.', N'17344689')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (32, N'Schuh-Hans s.r.o. v likvidaci', N'Společnost s r.o.', N'25482726')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (42, N'Jasmin prague s.r.o.', N'Společnost s r.o.', N'24307645')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (52, N'AQUACHEM, s.r.o.', N'Společnost s r.o.', N'61972266')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (62, N'PEDMARIVA s.r.o.', N'Společnost s r.o.', N'7039441')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (72, N'MAROFYLY s.r.o. v likvidaci', N'Společnost s r.o.', N'27561160')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (82, N'Fortica s.r.o.', N'Společnost s r.o.', N'6757715')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (92, N'SG Hydrogen Skoranov s.r.o.', N'Společnost s r.o.', N'14222990')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (102, N'POSTER Infinity s.r.o.', N'Společnost s r.o.', N'28502680')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (112, N'ExcelTown, s.r.o.', N'Společnost s r.o.', N'5341311')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (122, N'Volk Wood s.r.o.', N'Společnost s r.o.', N'26027771')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (132, N'DENIM FACTORY s.r.o.', N'Společnost s r.o.', N'28254066')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (142, N'B.K.AUDIT KYJOV, s.r.o.', N'Společnost s r.o.', N'46963006')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (152, N'ČAS - SERVICE a.s.', N'Akciová společnost', N'46346716')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (162, N'" SWIM spol. s r.o. ", v likvidaci', N'Společnost s r.o.', N'60277912')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (172, N'Orange automat s.r.o.', N'Společnost s r.o.', N'25559770')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (182, N'PS Trade Invest s.r.o.', N'Společnost s r.o.', N'4558791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (192, N'DEXO STAV s.r.o. v likvidaci', N'Společnost s r.o.', N'5819351')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (202, N'SUMEREN Consulting a.s.', N'Akciová společnost', N'24271969')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (212, N'AGORA fotovoltaika s.r.o.', N'Společnost s r.o.', N'4171691')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (222, N'SPORT U ANDĚLA, spol. s r.o.', N'Společnost s r.o.', N'63989557')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (232, N'Trans Europe Chemicals s.r.o. v likvidaci', N'Společnost s r.o.', N'25680978')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (242, N'BÍLÁ VRÁNA, s.r.o., v likvidaci', N'Společnost s r.o.', N'25783645')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (252, N'TRITOMA s.r.o. v likvidaci', N'Společnost s r.o.', N'63485699')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (262, N'Základní organizace Odborové organizace Pro Libertate - MMN', N'Odborová organizace', N'14245787')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (272, N'Malagueta s.r.o.', N'Společnost s r.o.', N'29015308')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (282, N'SOFILANAS s.r.o.', N'Společnost s r.o.', N'28191765')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (292, N'RaulWalter Service s. r. o.', N'Společnost s r.o.', N'14025299')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (3, N'Juglans regia s.r.o.', N'Společnost s r.o.', N'28898273')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (13, N'Leadblow s.r.o.', N'Společnost s r.o.', N'7748515')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (23, N'Sigmola s.r.o.', N'Společnost s r.o.', N'24668761')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (33, N'EXBYDO s.r.o.', N'Společnost s r.o.', N'62497791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (43, N'MEDITERRA - Sedlčany, s.r.o.', N'Společnost s r.o.', N'26429683')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (53, N'SHIN TRADE GROUP, spol. s r.o. v likvidaci', N'Společnost s r.o.', N'25737198')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (63, N'TEMPUS INVESTMENT a.s.', N'Akciová společnost', N'27379078')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (73, N'Amicus nimbus s. r. o.', N'Společnost s r.o.', N'9461493')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (83, N'MARIN DORO CZ s.r.o. v likvidaci', N'Společnost s r.o.', N'25789805')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (93, N'DURIT s.r.o. v likvidaci', N'Společnost s r.o.', N'46342541')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (103, N'ANCORA PRAHA, spol. s r.o.', N'Společnost s r.o.', N'48108073')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (113, N'CRACK Computers, s.r.o.', N'Společnost s r.o.', N'26426536')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (123, N'Hemp Solution s.r.o.', N'Společnost s r.o.', N'24309532')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (133, N'TLM Group s.r.o.', N'Společnost s r.o.', N'7802510')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (143, N'MIOPRO, spol. s r.o.', N'Společnost s r.o.', N'6243410')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (153, N'LIVE Call s.r.o.', N'Společnost s r.o.', N'6335128')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (163, N'SBC Central Europe, s.r.o.', N'Společnost s r.o.', N'28501608')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (173, N'AFCON POWER & AUTOMATION s.r.o.', N'Společnost s r.o.', N'27395545')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (183, N'LB-mir s.r.o.', N'Společnost s r.o.', N'27997049')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (193, N'NEJČI nábytek s.r.o.', N'Společnost s r.o.', N'25905465')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (203, N'KUWOOD s.r.o.', N'Společnost s r.o.', N'3240002')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (213, N'Ing. Ptáček - Elektro, s.r.o.', N'Společnost s r.o.', N'28502884')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (223, N'MS Holding s.r.o.', N'Společnost s r.o.', N'25418327')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (233, N'PressNow s.r.o.', N'Společnost s r.o.', N'17565430')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (243, N'Projects&Priorities s.r.o.', N'Společnost s r.o.', N'4346866')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (253, N'REFINEX s.r.o.', N'Společnost s r.o.', N'26495139')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (263, N'Energy & Industry Technologies, a.s.', N'Akciová společnost', N'6676391')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (273, N'RIBELL, s. r. o.', N'Společnost s r.o.', N'48590860')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (283, N'Odborové sdružení pracovníků SÚS Třebíč', N'Odborová organizace', N'3015271')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (293, N'strechy-kominy.cz, s. r. o.', N'Společnost s r.o.', N'28744098')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (4, N'PROBAT', N'Družstvo', N'25605542')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (14, N'I.S.M. Brno spol. s r.o., v likvidaci', N'Společnost s r.o.', N'49434250')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (24, N'EUROMONT OCEL s.r.o.', N'Společnost s r.o.', N'3039838')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (34, N'JO! Agency, s.r.o.', N'Společnost s r.o.', N'3297489')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (44, N'ALARM s.r.o., v likvidaci', N'Společnost s r.o.', N'25321862')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (54, N'E-state control s.r.o.', N'Společnost s r.o.', N'4616952')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (64, N'Viavelo s.r.o.', N'Společnost s r.o.', N'5795052')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (74, N'OXMED s.r.o.', N'Společnost s r.o.', N'1533932')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (84, N'VI - Value Innovation, s.r.o.', N'Společnost s r.o.', N'26853515')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (94, N'Dětský club Kosatka, z.ú.', N'Ústav', N'5635527')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (104, N'HE-DA, spol. s r.o.', N'Společnost s r.o.', N'62584987')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (114, N'Ecemerun s.r.o.', N'Společnost s r.o.', N'5036658')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (124, N'SBD START stavební bytové družstvo', N'Družstvo', N'530522')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (134, N'UXA spol. s r.o.', N'Společnost s r.o.', N'44013353')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (144, N'LATIČKA spol. s r.o. v likvidaci', N'Společnost s r.o.', N'26181428')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (154, N'Pagewiser s.r.o.', N'Společnost s r.o.', N'2477807')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (164, N'VLTAVÍN HOLDING stavební podnik s.r.o.', N'Společnost s r.o.', N'48026921')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (174, N'LEMON TEA spol. s r.o."v likvidaci"', N'Společnost s r.o.', N'25856405')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (184, N'HULK Stavební Družstvo', N'Družstvo', N'6859542')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (194, N'CPI Group, a.s.', N'Akciová společnost', N'28192095')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (204, N'Vaše restaurace s.r.o.', N'Společnost s r.o.', N'6483526')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (214, N'Rodinné domy Veltruby s.r.o.', N'Společnost s r.o.', N'9737081')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (224, N'71KV s.r.o.', N'Společnost s r.o.', N'27155293')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (234, N'Sunware s.r.o.', N'Společnost s r.o.', N'26741989')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (244, N'ZM SERVIS MORAVIA, s.r.o.', N'Společnost s r.o.', N'27785807')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (254, N'Boasam s.r.o.', N'Společnost s r.o.', N'7015810')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (264, N'MAKALOVE s.r.o.', N'Společnost s r.o.', N'4885261')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (274, N'ZO OS UNIOS Teplo Přerov', N'Odborová organizace', N'70259771')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (284, N'ES-servis Veselí, s.r.o.', N'Společnost s r.o.', N'3498867')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (294, N'TECHNOLIT CZ s.r.o.', N'Společnost s r.o.', N'17153191')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (9, N'PPL Rubicon s.r.o.', N'Společnost s r.o.', N'28507291')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (19, N'D & H living s.r.o.', N'Společnost s r.o.', N'9491325')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (29, N'Simplecon s.r.o.', N'Společnost s r.o.', N'5824401')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (39, N'TROJA PARK INVESTMENTS, spol. s r. o.', N'Společnost s r.o.', N'49689134')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (49, N'Foama s.r.o.', N'Společnost s r.o.', N'7706481')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (59, N'OksichemK s.r.o.', N'Společnost s r.o.', N'17592071')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (69, N'Topenáři VOPO s.r.o.', N'Společnost s r.o.', N'5831989')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (79, N'VIF BAGS s.r.o.', N'Společnost s r.o.', N'9565256')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (89, N'Yellow & Blue, s.r.o.', N'Společnost s r.o.', N'25130757')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (99, N'5FÜNF s.r.o.', N'Společnost s r.o.', N'6456391')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (109, N'TELPROBIS, spol. s r.o. "v likvidaci"', N'Společnost s r.o.', N'64617173')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (119, N'DANDYLAND s.r.o.', N'Společnost s r.o.', N'26746468')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (129, N'Projektum s.r.o.', N'Společnost s r.o.', N'4431723')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (139, N'FLOHMARKT property  s.r.o.', N'Společnost s r.o.', N'27170128')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (149, N'DRAM spol. s r.o. "v likvidaci"', N'Společnost s r.o.', N'42766974')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (159, N'SVA TRADE spol. s r.o.', N'Společnost s r.o.', N'25307398')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (169, N'Pavel Ševčík, s.r.o.', N'Společnost s r.o.', N'3032973')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (179, N'VELVOT s.r.o. v likvidaci', N'Společnost s r.o.', N'27981291')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (189, N'SeaReal s.r.o.', N'Společnost s r.o.', N'27832970')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (199, N'TESAVE CZ s.r.o.', N'Společnost s r.o.', N'6869360')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (209, N'MAFAX spol. s r.o. v likvidaci', N'Společnost s r.o.', N'64049396')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (219, N'HRYLIP garant s.r.o.', N'Společnost s r.o.', N'8157260')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (229, N'DYMEXPHARM s.r.o.', N'Společnost s r.o.', N'6537626')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (239, N'NELA s.r.o.', N'Společnost s r.o.', N'49550390')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (249, N'JoJo park s.r.o.', N'Společnost s r.o.', N'28619251')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (259, N'GEKOM CZ s.r.o.', N'Společnost s r.o.', N'25590677')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (269, N'HZC spol.s r.o.', N'Společnost s r.o.', N'14802899')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (279, N'SkillAddicts s.r.o.', N'Společnost s r.o.', N'9227393')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (289, N'Honební společenstvo Hněvkovice', N'Honební společenstvo', N'71152512')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (299, N'FOXXY real s.r.o.', N'Společnost s r.o.', N'8976163')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (1, N'ELEGANCE KAŠTÁNEK s.r.o.', N'Společnost s r.o.', N'7447736')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (11, N'KOVOMAYR, spol. s r.o. v likvidaci', N'Společnost s r.o.', N'60851635')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (21, N'SERVIS & KOMFORT spol. s.r.o.', N'Společnost s r.o.', N'27888720')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (31, N'AZ TERRA s.r.o.', N'Společnost s r.o.', N'2973332')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (41, N'WAMAG, spol. s r.o.', N'Společnost s r.o.', N'48950301')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (51, N'Rohlik Group a.s.', N'Akciová společnost', N'9960678')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (61, N'FV Technic Rides s.r.o.', N'Společnost s r.o.', N'5852960')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (71, N'BCH - Build Clever House s.r.o.', N'Společnost s r.o.', N'5669723')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (81, N'PRINT CENTRUM SERVICE s.r.o.', N'Společnost s r.o.', N'2836165')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (91, N'Aethera Investments s.r.o.', N'Společnost s r.o.', N'6509681')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (101, N'Sekty Moravy a Čech s.r.o.', N'Společnost s r.o.', N'5257611')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (111, N'Europe wood company s.r.o.', N'Společnost s r.o.', N'28023846')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (121, N'Bytové družstvo CHLUMEC', N'Družstvo', N'25451791')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (131, N'Oetiker Czech Republik s.r.o.', N'Společnost s r.o.', N'44960930')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (141, N'PHATEX CZ spol. s r.o. v likvidaci', N'Společnost s r.o.', N'25776568')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (151, N'bicchiere s.r.o.', N'Společnost s r.o.', N'3931731')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (161, N'TOVL works s.r.o.', N'Společnost s r.o.', N'4046439')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (171, N'Danailya s.r.o.', N'Společnost s r.o.', N'28912276')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (181, N'great commerce s.r.o.', N'Společnost s r.o.', N'3218546')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (191, N'GILT s.r.o.', N'Společnost s r.o.', N'3439526')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (201, N'PF MERIT s.r.o.', N'Společnost s r.o.', N'26174456')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (211, N'MarCa StahlBau s.r.o.', N'Společnost s r.o.', N'11998491')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (221, N'Eco Bio Trade Group s.r.o.', N'Společnost s r.o.', N'24289264')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (231, N'Hong Yu s.r.o. v likvidaci', N'Společnost s r.o.', N'24667544')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (241, N'Kamelot trade s.r.o.', N'Společnost s r.o.', N'29160120')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (251, N'Ribo s.r.o.', N'Společnost s r.o.', N'1932438')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (261, N'Shamrock Investment Properties Praha, a.s., v likvidaci', N'Akciová společnost', N'26486989')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (271, N'K.U.S. Trade s.r.o.', N'Společnost s r.o.', N'5363705')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (281, N'CSHA s.r.o.', N'Společnost s r.o.', N'3892280')
INSERT INTO @Spolecnosti ([Id], [ObchodniJmeno], [PravniForma], [IC]) VALUES (291, N'Medicinashop s.r.o. v likvidaci', N'Společnost s r.o.', N'5756766')